### ISSUE TITLE
Automatic inference of "input outputs"

### ISSUE THREAD

**Issue by multimeric** [aCLImatise/CliHelpParser#10]
e.g. `--outfile out.fasta`. This is both an input, and an output file. This should be added to the same part of the `Command` model as the output in #9.

**Comment by multimeric** [comment]
@bernt-matthias can you comment here so I can assign you to this issue please? (https://github.blog/changelog/2019-06-25-assign-issues-to-issue-commenters/)

**Comment by bernt-matthias** [comment]
ping
